// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHxNGxvtiKvXyIe7rhMv1-RsYxOcvaOs',
    appId: '1:698998434802:web:d9e0068e57fd446a37596b',
    messagingSenderId: '698998434802',
    projectId: 'atomik-pos-e4504',
    authDomain: 'atomik-pos-e4504.firebaseapp.com',
    storageBucket: 'atomik-pos-e4504.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TuAgRwHhX_uNkpLfdTCX0fE74t14ivQ',
    appId: '1:698998434802:android:f10755230dd77ef637596b',
    messagingSenderId: '698998434802',
    projectId: 'atomik-pos-e4504',
    storageBucket: 'atomik-pos-e4504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAIeRmRd6-RzQMA6Zo_mfce90mxlMaYo',
    appId: '1:698998434802:ios:c458e2a96f637c8737596b',
    messagingSenderId: '698998434802',
    projectId: 'atomik-pos-e4504',
    storageBucket: 'atomik-pos-e4504.firebasestorage.app',
    iosBundleId: 'org.atomiklabs.kasway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAIeRmRd6-RzQMA6Zo_mfce90mxlMaYo',
    appId: '1:698998434802:ios:c458e2a96f637c8737596b',
    messagingSenderId: '698998434802',
    projectId: 'atomik-pos-e4504',
    storageBucket: 'atomik-pos-e4504.firebasestorage.app',
    iosBundleId: 'org.atomiklabs.kasway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoHxNGxvtiKvXyIe7rhMv1-RsYxOcvaOs',
    appId: '1:698998434802:web:a7e4a3932e1b857137596b',
    messagingSenderId: '698998434802',
    projectId: 'atomik-pos-e4504',
    authDomain: 'atomik-pos-e4504.firebaseapp.com',
    storageBucket: 'atomik-pos-e4504.firebasestorage.app',
  );

}