import 'dart:developer';
import 'dart:io';

import 'package:bloc/bloc.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'app/app.dart';
import 'app/simple_bloc_observer.dart';
import 'firebase_options.dart'; // This file is usually generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // If firebase_options.dart is not generated yet, you might need to run `flutterfire configure`
    // For now, we'll assume it exists or use a dummy/platform check if you haven't run it.
    // However, since we are scaffolding, we'll try to use the DefaultFirebaseOptions if available.
    // If not, we might fail here until `flutterfire configure` is run.
    // Given the `firebase init` failure, we might fallback to manual init or just basic init.

    // NOTE: Replace `DefaultFirebaseOptions.currentPlatform` with your actual generated options
    // or remove arguments if checking blindly (not recommended for prod).
    // For this scaffold, I will assume the user will run `flutterfire configure`.
    // If `firebase_options.dart` is missing, comment out the options parameter.

    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Setup Emulators for local development
    if (kDebugMode) {
      final String host = Platform.isAndroid ? '10.0.2.2' : 'localhost';

      try {
        await FirebaseAuth.instance.useAuthEmulator(host, 9099);
        FirebaseFirestore.instance.useFirestoreEmulator(host, 8080);
        // Add other emulators as needed (Functions, Storage, etc.)
        log('Using Firebase Emulators');
      } catch (e) {
        log('Failed to use Firebase Emulators: $e');
      }
    }
  } catch (e) {
    log('Firebase initialization failed: $e');
    // Continue running app even if Firebase fails, for UI dev purposes
  }

  Bloc.observer = const SimpleBlocObserver();

  runApp(const App());
}
